# Лабораторная работа 1

### Разделение массива на количественный и качественный

In [2]:
# импорт библиотек
import numpy as np
import pandas as pd
import scipy.stats as stats

In [3]:
# выгрузка данных
df_0 = pd.read_csv('V11.csv', sep=';', decimal=',')
df_0.head()

A6       A10   A13  A16      A18   A20   A21  A22    A23  A37     A40
0  key    coated  line  821  tabloid  1911  25.0   38  0.200   40  noband
1  key    coated  line  816  spiegel  1910  45.0   54  0.167   35  noband
2  key    coated  line  827  tabloid  1911  50.0   46  0.200   40  noband
3  key  uncoated  line  802  catalog  1910  47.5   52  0.267   33    band
4  key  uncoated  line  815  catalog  1911  50.0   60  0.300   40    band

In [4]:
# разделим на 2 датафрейма - качественные и количественные данные
df_1 = df_0.iloc[:, 0:6]
df_1['A40'] = df_0['A40']
#df_1.head()

df_2 = df_0.iloc[:, 6:10]
df_2['A40'] = df_0['A40']
df_2.head()

A21  A22    A23  A37     A40
0  25.0   38  0.200   40  noband
1  45.0   54  0.167   35  noband
2  50.0   46  0.200   40  noband
3  47.5   52  0.267   33    band
4  50.0   60  0.300   40    band

In [5]:
# Произведем калибровку качественных данных с учетом априорного шанса с поправкой Лапласа
# С помощью формулы мы получили числа в таблице Excel, вставим их в дф, изменив старые значения

# A6
replace_dict = {'key': 0.001311808, 'type': 1}
df_1['A6'] = df_1['A6'].replace(replace_dict)

# A10
replace_dict = {'coated': 0.00200664, 'uncoated': 0.002898667, 'super': 1}
df_1['A10'] = df_1['A10'].replace(replace_dict)

# A13
replace_dict = {'line': 0.001308837, 'xylol': 0.176470588, 'lactol': 1, 'naptha': 0.076923077, 'other': 1}
df_1['A13'] = df_1['A13'].replace(replace_dict)

# A16
replace_dict = {821: 0.021956088, 802: 0.007407407, 813: 0.005544006, 
                824: 0.003076923, 815: 0.016248154, 816: 0.00752909, 
                827: 0.009784736, 828: 0.011124845
}
df_1['A16'] = df_1['A16'].replace(replace_dict)

# A18
replace_dict = {'tabloid': 0.00255052, 'spiegel': 0.009983361, 'catalog': 0.003649231}
df_1['A18'] = df_1['A18'].replace(replace_dict)

# A20
replace_dict = {1911: 0.004417834, 1910: 0.001846365, 'other': 1}
df_1['A20'] = df_1['A20'].replace(replace_dict)

df_1.head()

C:\Users\Екатерина\AppData\Local\Temp\ipykernel_9128\914489761.py:6: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_1['A6'] = df_1['A6'].replace(replace_dict)
C:\Users\Екатерина\AppData\Local\Temp\ipykernel_9128\914489761.py:10: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_1['A10'] = df_1['A10'].replace(replace_dict)
C:\Users\Екатерина\AppData\Local\Temp\ipykernel_9128\914489761.py:14: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitl

A6       A10       A13       A16       A18       A20     A40
0  0.001312  0.002007  0.001309  0.021956  0.002551  0.004418  noband
1  0.001312  0.002007  0.001309  0.007529  0.009983  0.001846  noband
2  0.001312  0.002007  0.001309  0.009785  0.002551  0.004418  noband
3  0.001312  0.002899  0.001309  0.007407  0.003649  0.001846    band
4  0.001312  0.002899  0.001309  0.016248  0.003649  0.004418    band

In [22]:
# Проведем дискретизацию с равной частотой количественных данных
quantiles = [0, 0.2, 0.4, 0.6, 0.8, 1]

for column in df_2:
    if column != 'A40':

        # Получение уникальных квантилей
        q = df_2[column].quantile(quantiles)
        unique_quantiles = q.unique()
        print(unique_quantiles)

        # этот массив потом вставить можно в дф
        arr = []

        # сравнение каждого значения дф с границами инт-лов
        for value in df_2[column]:
            for i in range(len(unique_quantiles)):
                if i == 0 and unique_quantiles[i] <= value <= unique_quantiles[i+1]:
                    arr.append(i+1)
                    break
                if unique_quantiles[i] < value <= unique_quantiles[i+1]:
                    arr.append(i+1)

        # создание нового столбца
        df_2[f'{column}_dis'] = arr
        

# Вывод результата
print(df_2)



[25.  37.5 40.  47.  50.  72.5]
[35. 43. 48. 54. 58. 72.]
[0.133 0.2   0.267 0.3   0.333 0.533]
[30. 35. 40. 45.]
      A21  A22    A23  A37     A40  A21_dis  A22_dis  A23_dis  A37_dis
0    25.0   38  0.200   40  noband        1        1        1        2
1    45.0   54  0.167   35  noband        3        3        1        1
2    50.0   46  0.200   40  noband        4        2        1        2
3    47.5   52  0.267   33    band        4        3        2        1
4    50.0   60  0.300   40    band        4        5        3        2
..    ...  ...    ...  ...     ...      ...      ...      ...      ...
495  30.0   54  0.500   35  noband        1        3        5        1
496  52.5   62  0.433   35    band        5        5        5        1
497  52.0   40  0.300   40  noband        5        1        3        2
498  60.0   56  0.300   40    band        5        4        3        2
499  45.0   53  0.300   35  noband        3        3        3        1

[500 rows x 9 columns]


In [23]:
# преобразуем A40 в столбец с 0 и 1 в обоих дф
df_1['A40'] = df_1['A40'].apply(lambda x: 1 if x == 'band' else 0)
df_2['A40'] = df_2['A40'].apply(lambda x: 1 if x == 'band' else 0)
print(df_1)
print(df_2)

           A6       A10       A13       A16       A18       A20  A40
0    0.001312  0.002007  0.001309  0.021956  0.002551  0.004418    0
1    0.001312  0.002007  0.001309  0.007529  0.009983  0.001846    0
2    0.001312  0.002007  0.001309  0.009785  0.002551  0.004418    0
3    0.001312  0.002899  0.001309  0.007407  0.003649  0.001846    1
4    0.001312  0.002899  0.001309  0.016248  0.003649  0.004418    1
..        ...       ...       ...       ...       ...       ...  ...
495  0.001312  0.002007  0.001309  0.003077  0.002551  0.001846    0
496  0.001312  0.002899  0.001309  0.021956  0.002551  0.001846    1
497  0.001312  0.002899  0.001309  0.007529  0.003649  0.001846    0
498  0.001312  0.002899  0.176471  0.007529  0.003649  0.004418    1
499  0.001312  0.002007  0.001309  0.007529  0.002551  0.001846    0

[500 rows x 7 columns]
      A21  A22    A23  A37  A40  A21_dis  A22_dis  A23_dis  A37_dis
0    25.0   38  0.200   40    0        1        1        1        2
1    45.0   